Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -27,4 +27,8 @@ jobs:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
     - run: npm install
-    - run: timeout 20 node .
+    - name: no timeout
+      run: timeout 10 node . || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
+    
+    - name: timeout # We add or so that return code is not none-zero which causes pipeline to fail
+      run: timeout 10 node . || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
